## Assignment 1

In [1]:
import numpy as np
from datasets import load_dataset,concatenate_datasets

### Loading The Data

In [2]:
dataset = load_dataset('sst', trust_remote_code=True)

In [3]:
dataset['test'][10]

{'sentence': 'What really surprises about Wisegirls is its low-key quality and genuine tenderness .',
 'label': 0.625,
 'tokens': 'What|really|surprises|about|Wisegirls|is|its|low-key|quality|and|genuine|tenderness|.',
 'tree': '25|24|22|21|21|19|16|15|15|17|14|14|20|18|16|17|18|19|20|23|22|23|24|25|0'}

### Preprocessing

In [4]:
def map_class(value):
    return np.digitize(value, bins=[0.2, 0.4, 0.6, 0.8], right=False)

In [5]:
dataset_mapped = dataset.map(lambda example: {'label': map_class(example['label'])})

In [6]:
# Access the training set
train_data = concatenate_datasets([dataset_mapped['train'], dataset_mapped['validation']])
train_labels = np.array(train_data['label'],dtype=np.int8)

# Access the test set
test_data = dataset_mapped['test']
test_labels = np.array(test_data['label'],dtype=np.int8)

num_classes = 5

In [7]:
x = test_data[10]
x

{'sentence': 'What really surprises about Wisegirls is its low-key quality and genuine tenderness .',
 'label': 3.0,
 'tokens': 'What|really|surprises|about|Wisegirls|is|its|low-key|quality|and|genuine|tenderness|.',
 'tree': '25|24|22|21|21|19|16|15|15|17|14|14|20|18|16|17|18|19|20|23|22|23|24|25|0'}

### Part 1: Naïve Bayes 

#### Algorithm Implementation

In [8]:
def train_naive_bayes(D,num_classes):
     
    n_doc = len(D)  # Total number of documents/examples
    cls_prior = np.zeros(num_classes)  # Initialize class prior probabilities
    vocab = set()  # To store the vocabulary
    cls_word_cnt = np.array([{} for _ in range(num_classes)])  # Initialize class word counts

    # Loop through each example in the dataset
    for example in D:
        example_class = int(example["label"])  # Get the class label for the example
        cls_prior[example_class] += 1  # Count the number of documents for each class
        for word in example["tokens"].split("|"):  # Tokenize the example
            # Update word count for the corresponding class
            cls_word_cnt[example_class][word] = cls_word_cnt[example_class].get(word, 0) + 1
            vocab.add(word)  # Add word to the vocabulary
           
    cls_prior /= n_doc  # Calculate prior probabilities
    log_prior = np.log(cls_prior)  # Convert prior probabilities to log space
    
    vocab_size = len(vocab)
    cls_total_word_cnt = np.array([sum(cls_dict.values()) for cls_dict in cls_word_cnt])  # Total word count for each class
    
    # Calculate log likelihood with smoothing (Laplace smoothing)
    log_likelihood = np.array([
        {word: np.log((cls_dict.get(word,0) + 1) / (cls_total_word_cnt[i] + vocab_size)) for word in vocab} 
        for i, cls_dict in enumerate(cls_word_cnt)
    ])
    
    return log_prior, log_likelihood, vocab

def test_naive_bayes(test_doc,log_prior, log_likelihood,num_classes,vocab):
    sum_lg = np.zeros(num_classes)
    for c in range(num_classes):
        sum_lg[c] = log_prior[c]
        for word in test_doc.split():
            if word in vocab:
                sum_lg[c] += log_likelihood[c][word]
                
    return np.argmax(sum_lg)

In [9]:
log_prior, log_likelihood, vocab = train_naive_bayes(train_data,num_classes)

In [10]:
predictions = []
for doc in test_data:
    predictions.append(test_naive_bayes(doc["sentence"],log_prior, log_likelihood, num_classes, vocab))
    
predictions = np.array(predictions)

# Calculate the number of correct predictions
correct_predictions = np.sum(predictions == test_labels)
    
# Calculate accuracy
my_accuracy = correct_predictions / len(test_labels)

In [11]:
print(my_accuracy)

0.3995475113122172


#### Comparison with scikit learn

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report


# Define the pipeline
pipeline = Pipeline([
    ('vectorizer', CountVectorizer()), 
    ('classifier', MultinomialNB())
])

# Fit the pipeline to the training data
pipeline.fit(train_data["sentence"], train_labels)

# Make predictions on the test data
y_pred = pipeline.predict(test_data["sentence"])

# Evaluate
print("Accuracy:", accuracy_score(test_labels, y_pred))

Accuracy: 0.40497737556561086


### Part 2: Logistic Regression

#### Feature Representation

In [13]:
def get_bigrams_cnt(D):
    
    bigrams = {}
    for example in D:
        words_list = example["tokens"].split("|")
        for i in range(len(words_list)-1):
            bigram = words_list[i] + " " + words_list[i+1]
            if bigram not in bigrams:
                bigrams[bigram] = len(bigrams)
    
    return bigrams
                
def generate_feat(D,bigrams,num_classes):
    test_data_feat = np.zeros((len(D),len(bigrams)+1),dtype=np.int8)
    test_data_labels = np.zeros((len(D),num_classes),dtype=np.int8)
    for i,example in enumerate(D):
        test_data_labels[i][int(example["label"])] = 1
        words_list = example["tokens"].split("|")
        for j in range(len(words_list)-1):
            bigram = words_list[j] + " " + words_list[j+1]
            test_data_feat[i][bigrams[bigram]] = 1
            
        
    return test_data_feat ,test_data_labels     


In [14]:
bigrams = get_bigrams_cnt(train_data)
X,Y = generate_feat(train_data,bigrams,num_classes)
print(Y)

[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 ...
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]]


#### Algorithm Implementation

In [31]:
def loss(X_T:np.ndarray,Y_T:np.ndarray,W:np.ndarray,B:np.ndarray):
    soft_max = softmax(W,X_T,B)
    req_ind = np.argmax(Y_T, axis=0)  # Row indices of non-zero elements
    req_values = np.log(soft_max[req_ind, np.arange(soft_max.shape[1])])
    return -np.sum(req_values)

def softmax(W:np.ndarray,X_T:np.ndarray,B:np.ndarray):
    W_exp = np.exp(W @ X_T + B)
    W_exp_sum = np.sum(W_exp,axis = 0)
    
    return W_exp/W_exp_sum
    
def calculate_gradient(X:np.ndarray,X_T:np.ndarray,Y_T:np.ndarray,W:np.ndarray,B:np.ndarray):
    derivative = Y_T * (1 - softmax(W,X_T,B))
    
    # Identify the indices of non-zero entries in each column
    non_zero_rows = np.argmax(Y_T, axis=0)  # Row indices of non-zero elements
    non_zero_values = derivative[non_zero_rows, np.arange(derivative.shape[1])]  # Non-zero values in derivative
    
    # Vectorized calculation of dW
    dW = np.zeros((W.shape[0],W.shape[1]))
    np.add.at(dW, non_zero_rows, -non_zero_values[:, np.newaxis] * X)  # Efficient row-wise update
    # Calculate dB directly
    dB = -np.sum(derivative, axis=1)
     
    return  dW, dB.reshape(5, 1)
       
def logistic_regression(X:np.ndarray,Y:np.ndarray,num_classes,lr=0.0001,max_itr=100):
    num_examples, num_features = X.shape
    W = np.random.rand(num_classes,num_features)
    B = np.random.rand(num_classes,1)
    itr = 0
    X_T,Y_T = X.T, Y.T
    while itr < max_itr:
        dW, dB = calculate_gradient(X,X_T,Y_T,W,B)
        W -= lr * dW
        B -= lr * dB
        
        print(f"The loss = {loss(X_T,Y_T,W,B)}")
        
        itr+=1
        
    return W,B

In [30]:
logistic_regression(X,Y,num_classes,lr=1,max_itr=10)

42252.84297713096
66443.37935055693
78696.60686080961
61254.64158070224
85400.67496971713


(array([[1.02059047, 0.96749366, 0.67895187, ..., 0.70139251, 0.47084987,
         0.77739312],
        [0.59105106, 0.3644622 , 0.11989423, ..., 0.99658006, 0.94958111,
         0.50614942],
        [0.43494124, 0.92620912, 0.69498505, ..., 0.37714349, 0.89970112,
         0.00524143],
        [0.87068545, 0.18344192, 0.30527782, ..., 0.46769962, 0.96437839,
         0.15547353],
        [0.55544599, 0.1356119 , 0.28423066, ..., 0.49598179, 0.71267236,
         0.06370952]]),
 array([[59.62330055],
        [82.09219825],
        [76.20604668],
        [69.79429549],
        [69.92429818]]))

#### Comparison with scikit learn